language: php
sudo: false

php:
  - 7.3


cache:
  directories:
    - $HOME/.composer/cache

addons:
  chrome: stable
  sonarcloud:
    organization: "jj1216"
    token:
      secure: "3e46e2c3ee7c503780da01cbba85cd1a23e7d65d"

git:
  depth: false

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE laravel character set utf8mb4 collate utf8mb4_bin;"
  - mysql_upgrade -u root

install:
  - cp .env.example .env
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate --seed
  - php artisan dusk:chrome-driver

before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - php artisan serve &

script:
  - php artisan dusk
  - vendor/bin/phpunit --coverage-clover coverage.xml --log-junit test-report.xml
  - sonar-scanner