version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3.3-fpm-node
      - image: circleci/mysql:5.7-ram
        #command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: laravel
          MYSQL_HOST: 127.0.0.1
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD:
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            cp .env.example .env
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo -E docker-php-ext-install pdo pdo_mysql
      - run: sudo -E docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
      - run: sudo apt install -y mysql-client
      #- run: sudo apt-get install -i mysql-client

      # composer cache
      - restore_cache:
          keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # node cache
      - restore_cache:
          keys:
            - node-v3-{{ checksum "package.json" }}
            - node-v3-
      - run: yarn install
      - save_cache:
          key: node-v3-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn
      - run: composer dump-autoload
      # prepare the database
      - run:
          name: Mysql database
          command: mysql -h 127.0.0.1 -u root -e "CREATE DATABASE laravel character set utf8mb4 collate utf8mb4_bin;"

      - run: php artisan key:generate
      - run: php artisan db:seed --force
      - run: ./vendor/bin/phpcs --standard=PSR2 app/
      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true
      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
          environment:
            APP_URL: http://127.0.0.1:8000
