version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3.3-fpm-node
      - image: circleci/mysql:5.7-ram
     
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            cp .env.example .env
            
      - run: sudo apt update && sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip
      - run: sudo -E docker-php-ext-install pdo pdo_mysql
      - run: sudo -E docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
      - run: sudo apt install -y mysql-client
      - run: sudo apt-get install mysql-server


      # composer cache
      - restore_cache:
          keys:
          # "composer.lock" can be used if it is committed to the repo
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # node cache
      - restore_cache:
          keys:
            - node-v3-{{ checksum "package.json" }}
            - node-v3-
      - run: yarn install
      - save_cache:
          key: node-v3-{{ checksum "package.json" }}
          paths:
            - node_modules
            - ~/.yarn
      - run: composer dump-autoload
      
      - run: 
          name: Generate Database
          command: mysql -h 127.0.0.1 -P 3306 -u root -e "CREATE DATABASE laravel" 
    
      - run: php artisan key:generate
      - run: php artisan migrate --seed
      - run:
          name: Require Dusk
          command: composer require --dev laravel/dusk
          
      - run:
          name: Install Dusk
          command: php artisan dusk:install
 
      - run:
          name: Install Chrome Driver
          command: php artisan dusk:chrome-driver
      - run:
          name: Install Google Chrome
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update && sudo apt-get install -y google-chrome-stable
            sudo apt-get install -y xvfb
            sudo apt-get -qyy install dbus-x11
            # entry.sh
            sudo rm -f /var/lib/dbus/machine-id
            sudo mkdir -p /var/run/dbus
            sudo service dbus restart
            service dbus status
            export $(dbus-launch)
            export NSS_USE_SHARED_DB=ENABLED
            echo "-- INFO: DBUS_SESSION_BUS_ADDRESS=${DBUS_SESSION_BUS_ADDRESS}"
            #=> e.g. DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-APZO4BE4TJ,guid=6e9c098d053d3038cb0756ae57ecc885
            echo "-- INFO: DBUS_SESSION_BUS_PID=${DBUS_SESSION_BUS_PID}"

      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux 
          background: true

      - run:
          name: Run Laravel Server
          command: php artisan serve 
          background: true
      - run:
          name: Run Laravel Dusk Tests
          command: php artisan dusk
          environment:
            APP_URL: http://127.0.0.1:8000
